'use client';
import {useState} from 'react';
import {Save, X, RefreshCw} from 'lucide-react';
type Product={id:string;name:string;price:number};
export function OrderEditor({order,products,currency,locked,onSave,onCancel,onReload}:{order:any;products:Product[];currency:string;locked:boolean;onSave:(name:string,items:{id:string;qty:number}[])=>Promise<void>;onCancel:()=>void;onReload:()=>Promise<void>}){
 const [name,setName]=useState(order.name),[qty,setQty]=useState<Record<string,string>>(Object.fromEntries(order.items.map((i:any)=>[i.id,String(i.qty)]))),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const money=(v:number)=>new Intl.NumberFormat('ro-RO',{style:'currency',currency}).format(v/100);
 const total=products.reduce((s,p)=>s+p.price*(Number(qty[p.id])||0),0);
 return <form className="panel order-editor" onSubmit={async e=>{e.preventDefault();setError('');const items=products.map(p=>({id:p.id,qty:Number(qty[p.id]||0)}));if(items.some(i=>!Number.isInteger(i.qty)||i.qty<0||i.qty>999)){setError('Folosește cantități întregi între 0 și 999.');return;}if(!items.some(i=>i.qty>0)){setError('Păstrează cel puțin un produs. Pentru anulare, contactează organizatorul.');return;}setBusy(true);try{await onSave(name,items.filter(i=>i.qty>0));}catch(e){setError(e instanceof Error?e.message:'Salvarea a eșuat.');}finally{setBusy(false);}}}><div className="section-heading"><h2>Modifică comanda: {order.name}</h2><button className="icon-button" type="button" disabled={busy} onClick={onCancel} aria-label="Închide editarea"><X/></button></div>{locked&&<p className="menu-warning">Comanda de grup este închisă. Doar organizatorul poate modifica acum cantitățile.</p>}<label>Nume<input required maxLength={80} value={name} disabled={locked||busy} onChange={e=>setName(e.target.value)}/></label><p className="muted">Introdu 0 pentru a elimina un produs din comandă.</p>{products.map(p=><div className="order-edit-row" key={p.id}><label htmlFor={'edit-'+p.id}>{p.name}<span className="muted"> · {money(p.price)} / buc.</span></label><input id={'edit-'+p.id} type="number" min="0" max="999" step="1" value={qty[p.id]||''} placeholder="0" disabled={locked||busy} onChange={e=>setQty({...qty,[p.id]:e.target.value})}/><strong>{money(p.price*(Number(qty[p.id])||0))}</strong></div>)}<div className="total"><span>Total nou</span><strong>{money(total)}</strong></div>{error&&<div className="error" role="alert">{error}</div>}<div className="editor-buttons"><button type="submit" className="primary" disabled={locked||busy}><Save size={17}/>{busy?'Se salvează…':'Salvează modificările'}</button><button type="button" className="secondary" disabled={busy} onClick={onCancel}>Renunță</button><button type="button" className="secondary" disabled={busy} onClick={async()=>{if(!window.confirm('Reîncarci comanda? Modificările nesalvate vor fi pierdute.'))return;setBusy(true);setError('');try{await onReload();}catch(e){setError(e instanceof Error?e.message:'Reîncărcarea a eșuat.');}finally{setBusy(false);}}}><RefreshCw size={16}/>Reîncarcă</button></div></form>;
}
