'use client';
import {useState} from 'react';
import menu from '@/lib/griff-menu.json';
export type DraftProduct={name:string;price:string;image?:string;dailyMenu?:boolean};
export function FoodPhoto({src,name}:{src?:string;name:string}){
 const [failed,setFailed]=useState(false);
 return src&&!failed?<img className="food-photo" src={src} alt={name} loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<span className="food-photo photo-placeholder" aria-hidden="true">♨</span>;
}
export function RestaurantPicker({onApply}:{onApply:(rows:DraftProduct[],currency:string)=>string|null}){
 const [restaurant,setRestaurant]=useState('griff'),[selected,setSelected]=useState<string[]>(menu.map(p=>p.name)),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[includeDaily,setIncludeDaily]=useState(true);
 return <section className="menu-import"><h2>De unde comandăm?</h2><label>Restaurant<select value={restaurant} onChange={e=>{setRestaurant(e.target.value);setMessage('');}}><option value="">Alt restaurant / introducere manuală</option><option value="griff">Griff — meniu fix</option></select></label>{restaurant==='griff'&&<><p className="muted">56 de produse cu fotografii. Meniu preluat la 09.09.2026; prețurile nu se actualizează automat. <a href="https://griff.restaurant/menu" target="_blank" rel="noreferrer">Vezi meniul restaurantului</a>.</p><div className="griff-daily-preset"><label><input type="checkbox" checked={includeDaily} onChange={e=>setIncludeDaily(e.target.checked)}/> Include Meniul zilei Griff — 35,00 lei</label><p>Colegii aleg obligatoriu ciorba, felul 2, garnitura și salata. Poți debifa toate produsele fixe și adăuga doar meniul zilei.</p></div><label>Caută în meniu<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ciorbă, burger, clătite…"/></label><div className="preset-actions"><button type="button" className="text-button" onClick={()=>setSelected(menu.map(p=>p.name))}>Selectează tot</button><button type="button" className="text-button" onClick={()=>setSelected([])}>Debifează tot</button><span>{selected.length} selectate</span></div><div className="preset-list">{menu.filter(p=>p.name.toLocaleLowerCase('ro').includes(query.toLocaleLowerCase('ro'))).map(p=><label className="preset-row" key={p.name}><input type="checkbox" checked={selected.includes(p.name)} onChange={e=>setSelected(e.target.checked?[...selected,p.name]:selected.filter(n=>n!==p.name))}/><FoodPhoto src={p.image} name={p.name}/><span>{p.name}</span><b>{Number(p.price).toFixed(2)} lei</b></label>)}</div><button type="button" className="secondary" disabled={!selected.length&&!includeDaily} onClick={()=>{const error=onApply([...menu.filter(p=>selected.includes(p.name)),...(includeDaily?[{name:'Meniul zilei Griff',price:'35.00',dailyMenu:true}]:[])],'RON');setMessage(error||'Produsele Griff au fost adăugate. Le poți modifica mai jos.');}}>Folosește selecția Griff ({selected.length+(includeDaily?1:0)})</button><p className="small muted">Confirmă oferta zilei cu restaurantul înainte de a distribui lista. Fotografii: Griff / OutOrdering.</p></>}{message&&<p role="status">{message}</p>}</section>;
}

export function DailyMenu({currency,onApply}:{currency:string;onApply:(rows:DraftProduct[],currency:string)=>string|null}){
 const [mode,setMode]=useState('complete'),[name,setName]=useState(''),[price,setPrice]=useState(''),[parts,setParts]=useState([{name:'',price:''},{name:'',price:''}]),[message,setMessage]=useState('');
 function add(){
  const rows:DraftProduct[]=[];
  if(mode!=='separate')rows.push({name:'Meniul zilei — '+name.trim(),price});
  if(mode!=='complete')rows.push(...parts.filter(p=>p.name.trim()).map(p=>({name:'Separat — '+p.name.trim(),price:p.price})));
  if((mode!=='separate'&&!name.trim())||!rows.length||rows.some(p=>!p.price.trim()||!Number.isFinite(Number(p.price))||Number(p.price)<0||Number(p.price)>100000||p.name.length>200)){setMessage('Completează denumirea și prețul fiecărei variante oferite.');return;}
  const error=onApply(rows,currency);setMessage(error||'Variantele au fost adăugate în listă. Poți adăuga și alte combinații.');
 }
 return <details className="menu-import"><summary><b>Meniul zilei — complet sau pe feluri</b></summary><p className="muted">Alege doar variantele pe care restaurantul le vinde. Pentru mai multe combinații, adaugă fiecare variantă ca produs; colegii bifează varianta și cantitatea.</p><label>Ce se poate comanda?<select value={mode} onChange={e=>{setMode(e.target.value);setMessage('');}}><option value="complete">Doar meniul complet</option><option value="separate">Doar feluri separate</option><option value="both">Meniu complet și feluri separate</option></select></label>{mode!=='separate'&&<div className="daily-row"><label>Conținutul variantei de meniu<input maxLength={180} value={name} onChange={e=>setName(e.target.value)} placeholder="Ciorbă de pui + șnițel + piure + salată"/></label><label>Preț complet ({currency})<input type="number" min="0" max="100000" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label></div>}{mode!=='complete'&&<>{parts.map((p,i)=><div className="daily-row" key={i}><label>Fel separat {i+1}<input maxLength={180} value={p.name} onChange={e=>setParts(parts.map((v,j)=>j===i?{...v,name:e.target.value}:v))} placeholder={i===0?'Ciorbă de pui':'Șnițel cu piure'}/></label><label>Preț separat ({currency})<input type="number" min="0" max="100000" step="0.01" value={p.price} onChange={e=>setParts(parts.map((v,j)=>j===i?{...v,price:e.target.value}:v))}/></label></div>)}<button type="button" className="text-button" disabled={parts.length>=10} onClick={()=>setParts([...parts,{name:'',price:''}])}>+ Alt fel separat</button></>}<p className="small muted">Griff afișa meniul complet la 35 lei la verificarea din 09.09.2026. Confirmă oferta actuală și prețurile separate; prețul complet nu se împarte automat.</p><button type="button" className="secondary" onClick={add}>Adaugă variantele în listă</button>{message&&<p role="status">{message}</p>}</details>;
}
